In [1]:
# Q1 What will be the output of the following code?
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [3]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result

#12_dist(np.reshape(a,(20*20)), np.reshape(b,(20*20,1)))
12_dist(a.T,b.T)

SyntaxError: invalid decimal literal (<ipython-input-3-a854bfc6a8f3>, line 7)

In [11]:
import numpy as np

a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)
print(a1)
print(a2)

print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a4.shape)
print(a5.shape)

[0.58031787 0.48252831 0.39650235 0.90636894]
[[0.61258042]
 [0.04476757]
 [0.79503473]
 [0.66941662]]
(4,)
(4, 1)
(1, 4)
(3,)
(4,)


In [12]:
#Q4 Which of the following is the correct output for the code given below?
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0
print(old)

[[0 0 1]
 [1 1 1]]


In [17]:
#Q6 For the given string, which of the following regular expressions can be used to check if the string starts with 'AC'?
import re
s = 'ACBCAC'

re.findall('^AC',s)

['AC']

In [20]:
# Q6 What will be the output of the variable L after the following code is executed?
import re

s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
print(result)
L = len(result)
print(L)

['A', 'AA', 'AA', 'AA', 'A']
5


In [25]:
#Q10
text=r'''Everyone has the following fundamental freedoms:
(a) freedom of conscience and religion;
(b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
(c) freedom of peaceful assembly; and
(d) freedom of association.
'''

import re

#pattern = 'freedom'
pattern = '\(.\)'

print(len(re.findall(pattern,text)))

4
